### ISSUE TITLE
> node server.js  module.js:338     throw err;           ^ Error: Cannot find module './config/config'

### ISSUE THREAD

**Issue by tomachinz** [diki/nodejs-passport-boilerplate#9]
Anybody know what I'm doing wrong here? I've cloned the repo, then done npm install, and then straight to npm start without making any changes to the config files - since I've no idea how to. Is there a page about how to set the config files? 

> node server.js

module.js:338
    throw err;
          ^
Error: Cannot find module './config/config'v

**Comment by diki** [comment]
Create a config.js file under config folder, it should work then.
